services:
  app:
    build:
      dockerfile_inline: |
        FROM ruby:bullseye
        COPY Gemfile Gemfile.lock .
        RUN bundle install
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 4000:4000
    command: bundle exec jekyll serve -H 0.0.0.0 --watch
